In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import  r2_score , f1_score,confusion_matrix
import pandas as pd

In [2]:
# Membuat data sederhana
x_train = np.array([1, 2, 3, 4, 5, 6], dtype=float)  # Jumlah kamar
y_train = np.array([100, 150, 200, 250, 300, 350], dtype=
                   
                   float)  # Harga dalam ribuan dolar



In [3]:
# Membuat model Sequential
model = keras.Sequential([
    layers.Dense(units=1, input_shape=[1])
])

d:\cursor_code\python\Lstm\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(x_train, y_train, epochs=500)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 57696.3242
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 26838.4277
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 12555.4834
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5943.9321
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2882.9407
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1465.2603
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 808.1618
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 503.0898
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 360.9531
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 294.2347
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 262.4287
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 246.7882
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 238.6362
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 233.9568
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/st

In [5]:
print(model.predict(np.array([8.0])))  # Memprediksi harga rumah dengan 7 kamar

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[455.07687]]


In [7]:
x = np.array([1, 2, 3, 4, 5, 6], dtype=float)  # Jumlah kamar
y = np.array([100, 150, 200, 250, 300, 350], dtype=float)  # Harga dalam ribuan dolar

In [14]:
X_train , X_test , y_train , y_test = train_test_split(x,y)
print(X_train)
print(y_train)

[6. 1. 2. 4.]
[350. 100. 150. 250.]


In [15]:
models = keras.Sequential([
    layers.Dense(units=1, input_shape=[1])
])


Epoch 1/500


d:\cursor_code\python\Lstm\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step - loss: 55878.9414
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 27544.2969
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 13662.0107
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 6859.6831
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3525.7124
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1890.8423
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1088.3452
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 693.6271
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 498.6888
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 401.6336
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 352.5454
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 326.9702
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 312.9285
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 304.5519
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss:

In [ ]:
models.compile(optimizer='sgd', loss='mean_squared_error')
models.fit(X_train, y_train, epochs=500)

In [27]:
y_pred = models.predict(X_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[300.49475],
       [199.06274]], dtype=float32)

In [24]:
new_data = np.array([7])
pred = model.predict(new_data)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[403.71167]], dtype=float32)

In [31]:
from  sklearn.metrics import r2_score , accuracy_score

score = r2_score(y_pred,y_test)
score

0.9997816528524277